---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "ide.fullname" . }}-role
rules:
  - apiGroups: 
      - "" # indicates the core API group
      - "apps"
    resources:
      - endpoints
      - deployments
      - pods
    verbs:
      - get
      - list
      - delete
      - watch
      - create
      - update
      - patch

  - apiGroups: 
      - "" # indicates the core API group
    resources:
      - pods/log
    verbs:
      - get
      - list

  - apiGroups: 
    - "" # indicates the core API group
    resources: 
    - services
    verbs: 
      - get
      - list
      - delete
      - watch
      - create
      - update
      - patch

  - apiGroups: 
      - "batch"
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - delete
      - watch
      - create
      - update
      - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "ide.fullname" . }}-binding
subjects:
  - kind: ServiceAccount
    name: {{ template "ide.fullname" . }}-sa
roleRef:
  kind: Role
  name: {{ template "ide.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
---
# kind: ClusterRoleBinding
# apiVersion: rbac.authorization.k8s.io/v1
# metadata:
#   name: {{ template "ide.fullname" . }}
#   #namespace: ${NAMESPACE}  
# subjects:
# - kind: ServiceAccount
#   name: {{ template "ide.fullname" . }}
#   #namespace: ${NAMESPACE}  
# roleRef:
#   kind: ClusterRole
#   name: {{ template "ide.fullname" . }}
#   apiGroup: rbac.authorization.k8s.io

#
# https://kubernetes.io/docs/reference/access-authn-authz/rbac/
#