apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sqlpad.fullname" . }}
  labels:
    app: {{ template "sqlpad.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "sqlpad.name" . }}
      release: {{ .Release.Name }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "sqlpad.name" . }}
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.global.env_name }}-{{ .Values.global.regsecret }}    
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.name }}:{{ .Values.image.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          env: 
            - name: PASSWORD
              value: "{{ .Values.password }}"
            - name: STARTUP_SCRIPT
              value: "{{ .Values.startup_script }}"          
              
      


