apiVersion: v1
appVersion: 1.0.0
description: null
name: ndru-code
version: 1.0.39
keywords:
  - cw
  - ndru
  - coding
  - tools
home: https://github.com/chimpwizards
icon: 'https://www.freeiconspng.com/uploads/sql-file-icon-0.png'
maintainers:
  - name: ndru
    email: ndru@chimpwizard.com
    url: https://github.com/chimpwizards
dependencies:
  - name: sqlpad
    version: 0.1.0
