version: '3'

services:
  code:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UNIT_TEST=yes
        - PUBLISH=yes
        - PUSH_PWD=${PUSH_PWD}
    image: '${BUILD_IMAGE}'
